import {
  Account,
  HomeActivity,
  HomeSummary,
  PayoutCurrency,
  PayoutNetwork,
  UserProfile,
} from "./types";
import { generateMockAccounts } from "./generate-accounts";

// MOCK ACCOUNTS
export const mockAccounts: Account[] = [
  // SELF - BANK ACCOUNTS
  {
    id: "acc_001",
    name: "John Doe",
    nickname: "Primary Checking",
    type: "bank",
    ownership: "self",
    bankName: "Bank of America",
    lastFour: "3848",
    accountType: "checking",
    currency: PayoutCurrency.USD,
    countryCode: "us",
    status: "active",
    createdAt: new Date("2024-01-15"),
    lastUsedAt: new Date("2026-02-03"),
    isDefault: true,
  },
  {
    id: "acc_002",
    name: "MoneyX Business",
    nickname: "Business Operations",
    type: "bank",
    ownership: "self",
    bankName: "Chase",
    lastFour: "9921",
    accountType: "business",
    currency: PayoutCurrency.USD,
    countryCode: "us",
    status: "active",
    createdAt: new Date("2024-03-20"),
    lastUsedAt: new Date("2026-02-02"),
  },
  {
    id: "acc_003",
    name: "Mexico Operations",
    type: "bank",
    ownership: "self",
    bankName: "BBVA Mexico",
    lastFour: "3184",
    accountType: "business",
    currency: PayoutCurrency.MXN,
    countryCode: "mx",
    status: "active",
    createdAt: new Date("2024-06-10"),
    lastUsedAt: new Date("2026-01-12"),
  },

  // SELF - CRYPTO WALLETS
  {
    id: "acc_004",
    name: "Treasury Wallet",
    nickname: "Main USDC",
    type: "crypto",
    ownership: "self",
    network: PayoutNetwork.SOL,
    walletAddress: "K5Rb7hGxPQmNvE8dJwYf2TcL9sAzXkWq4UoMiHnBEH6b",
    currency: PayoutCurrency.USDC,
    status: "active",
    createdAt: new Date("2024-02-01"),
    lastUsedAt: new Date("2026-01-29"),
    isDefault: true,
  },
  {
    id: "acc_005",
    name: "Hot Wallet",
    type: "crypto",
    ownership: "self",
    network: PayoutNetwork.ETH,
    walletAddress: "0x7F2c9E8b4A3D6f1C5e0B9d8E7F2a4C6b8D0e2F4a",
    currency: PayoutCurrency.USDC,
    status: "active",
    createdAt: new Date("2024-04-15"),
    lastUsedAt: new Date("2025-10-01"),
  },
  {
    id: "acc_006",
    name: "Base Bridge Wallet",
    type: "crypto",
    ownership: "self",
    network: PayoutNetwork.BASE,
    walletAddress: "0xaB3c4D5e6F7a8b9c0D1e2F3a4B5c6D7e8F9a0B1c",
    currency: PayoutCurrency.USDC,
    status: "pending",
    createdAt: new Date("2025-01-30"),
  },

  // RECIPIENTS - BANK ACCOUNTS
  {
    id: "acc_007",
    name: "Carlos Silva",
    nickname: "Brazil Supplier",
    type: "bank",
    ownership: "recipient",
    bankName: "Itau Unibanco",
    lastFour: "7712",
    accountType: "checking",
    currency: PayoutCurrency.BRL,
    countryCode: "br",
    status: "active",
    createdAt: new Date("2024-08-01"),
    lastUsedAt: new Date("2026-02-02"),
  },
  {
    id: "acc_008",
    name: "Global Payments Ltd",
    type: "bank",
    ownership: "recipient",
    bankName: "Wells Fargo",
    lastFour: "3301",
    accountType: "business",
    currency: PayoutCurrency.USD,
    countryCode: "us",
    status: "active",
    createdAt: new Date("2024-09-15"),
    lastUsedAt: new Date("2025-12-10"),
  },
  {
    id: "acc_009",
    name: "Mexico Contractor",
    type: "bank",
    ownership: "recipient",
    bankName: "BBVA Mexico",
    lastFour: "5582",
    accountType: "checking",
    currency: PayoutCurrency.MXN,
    countryCode: "mx",
    status: "active",
    createdAt: new Date("2025-10-20"),
    lastUsedAt: new Date("2026-01-22"),
  },

  // RECIPIENTS - CRYPTO WALLETS
  {
    id: "acc_010",
    name: "Vendor Wallet",
    nickname: "Monthly Contractor",
    type: "crypto",
    ownership: "recipient",
    network: PayoutNetwork.SOL,
    walletAddress: "9xKvMpNqR2sT4uW6yZ8aB0cD2eF4gH6iJ8kL0mN2oP4q",
    currency: PayoutCurrency.USDC,
    status: "active",
    createdAt: new Date("2024-10-01"),
    lastUsedAt: new Date("2025-01-31"),
  },
  {
    id: "acc_011",
    name: "Exchange Deposit",
    nickname: "Kraken",
    type: "crypto",
    ownership: "recipient",
    network: PayoutNetwork.ETH,
    walletAddress: "0x1a2B3c4D5e6F7a8b9c0D1e2F3a4B5c6D7e8F9a0B",
    currency: PayoutCurrency.USDT,
    status: "inactive",
    createdAt: new Date("2024-05-20"),
    lastUsedAt: new Date("2024-12-15"),
  },
  {
    id: "acc_012",
    name: "Polygon Settlement",
    type: "crypto",
    ownership: "recipient",
    network: PayoutNetwork.POLYGON,
    walletAddress: "0xDef456Abc789Def012Abc345Def678Abc901Def23",
    currency: PayoutCurrency.USDC,
    status: "active",
    createdAt: new Date("2024-11-10"),
    lastUsedAt: new Date("2026-01-18"),
  },
];

// All accounts: original 12 + 1000 generated
export const allMockAccounts: Account[] = [
  ...mockAccounts,
  ...generateMockAccounts(1000),
];

// Home page mock data
export const mockHomeSummary: HomeSummary = {
  monthlyTransferred: 12450,
  lastMonthTransferred: 10320,
};

export const mockHomeActivity: HomeActivity[] = [
  {
    id: "tx_001",
    to: "Carlos Silva",
    amount: 1000,
    currency: PayoutCurrency.USD,
    recipientAmount: 5270,
    recipientCurrency: PayoutCurrency.BRL,
    status: "completed",
    sentAt: new Date("2026-02-02"),
    type: "bank",
    bankName: "Itau Unibanco",
  },
  {
    id: "tx_002",
    to: "Treasury Wallet",
    amount: 500,
    currency: PayoutCurrency.USDC,
    recipientAmount: 500,
    recipientCurrency: PayoutCurrency.USDC,
    status: "completed",
    sentAt: new Date("2026-01-29"),
    type: "crypto",
    network: PayoutNetwork.SOL,
  },
  {
    id: "tx_003",
    to: "Mexico Contractor",
    amount: 425.29,
    currency: PayoutCurrency.USD,
    recipientAmount: 7400,
    recipientCurrency: PayoutCurrency.MXN,
    status: "pending",
    sentAt: new Date("2026-01-22"),
    type: "bank",
    bankName: "BBVA Mexico",
  },
  {
    id: "tx_004",
    to: "Polygon Settlement",
    amount: 850,
    currency: PayoutCurrency.USDC,
    recipientAmount: 850,
    recipientCurrency: PayoutCurrency.USDC,
    status: "completed",
    sentAt: new Date("2026-01-18"),
    type: "crypto",
    network: PayoutNetwork.POLYGON,
  },
];

export const mockUserProfile: UserProfile = {
  name: "John Doe",
  initials: "JD",
  organization: "MoneyX",
  plan: "Enterprise",
  email: "jdoe@moneyx.com",
  kybStatus: "Verified",
  kybVerifiedAt: new Date("2024-01-20"),
  customerId: "customer_916725ea2ed34acbab9b8b92b9802284",
  phone: "+1 777-777-7777",
};
